[package]
name = "cuda_base"
version = "0.0.0"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0.93", features = ["full", "visit", "visit-mut"] }
proc-macro2 = "1.0"
rustc-hash = "1.1"
